# Generated by Django 4.2.7 on 2026-03-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('school', 'School'), ('kindergarten', 'Kindergarten'), ('ssv', 'SSV Institution')], max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', max_length=10)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type'], name='institution_type_2be4c5_idx'), models.Index(fields=['region', 'district'], name='institution_region_1573de_idx'), models.Index(fields=['status'], name='institution_status_fc2138_idx'), models.Index(fields=['name'], name='institution_name_ccaed3_idx')],
            },
        ),
    ]
