# Generated by Django 4.2.7 on 2026-03-14 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0001_initial'),
        ('promises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promise',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promises', to='institutions.institution'),
        ),
        migrations.AddIndex(
            model_name='promise',
            index=models.Index(fields=['institution', 'status'], name='promises_pr_institu_803b51_idx'),
        ),
    ]
