# Generated by Django 4.2.7 on 2026-03-14 11:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, db_index=True, help_text='Anonymous if null', null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address_name', models.CharField(blank=True, help_text='Auto-filled via reverse geocoding', max_length=500, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete — NULL means active', null=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_reports', to='institutions.institution')),
            ],
            options={
                'db_table': 'construction_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='constructio_status_f2f8a7_idx'), models.Index(fields=['severity'], name='constructio_severit_09c44f_idx'), models.Index(fields=['deleted_at'], name='constructio_deleted_bc9f10_idx'), models.Index(fields=['-created_at'], name='constructio_created_f34050_idx'), models.Index(fields=['like_count'], name='constructio_like_co_c5cb7a_idx'), models.Index(fields=['view_count'], name='constructio_view_co_07f467_idx')],
            },
        ),
    ]
