# Generated by Django 4.2.7 on 2026-03-14 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0001_initial'),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='problem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='problemverification',
            unique_together={('problem', 'user')},
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['institution', 'status'], name='problems_pr_institu_38abe4_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['category'], name='problems_pr_categor_db58d6_idx'),
        ),
    ]
